services:
  backend:
    # Constrói a partir do contexto raiz (.), usando o Dockerfile.backend
    build:
      context: .
      dockerfile: Dockerfile.backend
    env_file:
      - ./.env # Lê variáveis da raiz
    ports:
      - "8000:8000" # Mapeia porta do backend
    # volumes:
    #   # (Opcional) Monta o código da API para live reload local, se necessário
    #   # CUIDADO: Isso pode sobrescrever dependências instaladas na imagem
    #   # - ./api:/app
    #   pass # Remover pass

  frontend:
    # Constrói a partir do contexto raiz (.), usando o Dockerfile.frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80" # Mapeia porta do frontend (Nginx)
    depends_on:
      - backend # Garante que o backend inicie primeiro

networks: # Opcional, mas boa prática definir uma rede
  default:
    driver: bridge